from django.conf.urls import url
from inventory.views import (
    ActCreate,
    ActDelete,
    ActUpdate,
    ActivateTheme,
    BulkImageUpload,
    BulkItemUpload,
    CategoryCreate,
    CategoryDelete,
    CategoryListView,
    CategoryUpdate,
    CloneTheme,
    DeleteTheme,
    ItemDelete,
    ItemsListView,
    MakeItemWizard,
    ManageItemImage,
    ManageTheme,
    MergeCategories,
    MergeTags,
    PerformerCreate,
    PerformerDelete,
    PerformerUpdate,
    PreviewTheme,
    PromoteItemImage,
    ShowCreate,
    ShowDelete,
    ShowUpdate,
    SubitemCreate,
    SubitemDelete,
    SubItemsListView,
    SubitemUpdate,
    TagCreate,
    TagDelete,
    TagListView,
    TagUpdate,
    ThemeView,
    ThemesListView,
)


app_name = "inventory"

urlpatterns = [
    # Acts
    url(r'^inventory/act/create/?',
        ActCreate.as_view(),
        name='act_create'),
    url(r'^inventory/act/delete/(?P<pk>.*)/$',
        ActDelete.as_view(),
        name='act_delete'),
    url(r'^inventory/act/update/(?P<pk>.*)/$',
        ActUpdate.as_view(),
        name='act_update'),

    # Categories
    url(r'^inventory/category/list/?',
        CategoryListView.as_view(),
        name='categories_list'),
    url(r'^inventory/category/create/?',
        CategoryCreate.as_view(),
        name='category_create'),
    url(r'^inventory/category/delete/(?P<pk>.*)/$',
        CategoryDelete.as_view(),
        name='category_delete'),
    url(r'^inventory/category/update/(?P<pk>.*)/$',
        CategoryUpdate.as_view(),
        name='category_update'),
    url(r'^inventory/category/merge/?',
        MergeCategories.as_view(),
        name='category_merge'),

    # Items
    url(r'^inventory/item/list/?', ItemsListView.as_view(), name='items_list'),
    url(r'^inventory/item/upload/?',
        BulkItemUpload.as_view(),
        name='item_upload'),
    url(r'^inventory/item/delete/(?P<pk>.*)/$',
        ItemDelete.as_view(),
        name='item_delete'),
    url(r'^inventory/item/create/?',
        MakeItemWizard.as_view(),
        name='item_create'),
    url(r'^inventory/item/edit/(?P<item_id>\d+)/?',
        MakeItemWizard.as_view(),
        name='item_edit'),

    # Image/items
    url(r'^inventory/image/upload/?',
        BulkImageUpload.as_view(),
        name='image_upload'),
    url(r'^inventory/image/promote/(?P<itemimage_id>\d+)/?',
        PromoteItemImage.as_view(),
        name='promote_item_image'),
    url(r'^inventory/item/images/(?P<item_id>\d+)/?',
        ManageItemImage.as_view(),
        name='manage_item_image'),

    # Performers
    url(r'^inventory/performer/create/?',
        PerformerCreate.as_view(),
        name='performer_create'),
    url(r'^inventory/performer/delete/(?P<pk>.*)/$',
        PerformerDelete.as_view(),
        name='performer_delete'),
    url(r'^inventory/performer/update/(?P<pk>.*)/$',
        PerformerUpdate.as_view(),
        name='performer_update'),

    # Show
    url(r'^inventory/show/create/?',
        ShowCreate.as_view(),
        name='show_create'),
    url(r'^inventory/show/delete/(?P<pk>.*)/$',
        ShowDelete.as_view(),
        name='show_delete'),
    url(r'^inventory/show/update/(?P<pk>.*)/$',
        ShowUpdate.as_view(),
        name='show_update'),

    # Themes
    url(r'^inventory/(?P<version_id>\d+)/style.css',
        ThemeView.as_view(),
        name='theme_style'),
    url(r'^inventory/style.css', ThemeView.as_view(), name='theme_style'),
    url(r'^inventory/theme/list/?',
        ThemesListView.as_view(),
        name='themes_list'),
    url(r'^inventory/activate/(?P<version_id>\d+)/(?P<target_system>[-\w]+)/?',
        ActivateTheme.as_view(),
        name='activate_theme'),
    url(r'^inventory/preview/(?P<version_id>\d+)/?',
        PreviewTheme.as_view(),
        name='preview_theme'),
    url(r'^inventory/preview/?',
        PreviewTheme.as_view(),
        name='preview_off'),
    url(r'^inventory/style_edit/(?P<version_id>\d+)/?',
        ManageTheme.as_view(),
        name='manage_theme'),
    url(r'^inventory/style_delete/(?P<version_id>\d+)/?',
        DeleteTheme.as_view(),
        name='delete_theme'),
    url(r'^inventory/style_clone/(?P<version_id>\d+)/?',
        CloneTheme.as_view(),
        name='clone_theme'),

    # Tags
    url(r'^inventory/tag/list/?',
        TagListView.as_view(),
        name='tags_list'),
    url(r'^inventory/tag/create/?', TagCreate.as_view(), name='tag_create'),
    url(r'^inventory/tag/delete/(?P<pk>.*)/$',
        TagDelete.as_view(),
        name='tag_delete'),
    url(r'^inventory/tag/update/(?P<pk>.*)/$',
        TagUpdate.as_view(),
        name='tag_update'),
    url(r'^inventory/tag/merge/?', MergeTags.as_view(), name='tag_merge'),

    # Subitems
    url(r'^inventory/subitem/list/?',
        SubItemsListView.as_view(),
        name='subitems_list'),
    url(r'^inventory/subitem/create/?',
        SubitemCreate.as_view(),
        name='subitem_create'),
    url(r'^inventory/subitem/delete/(?P<pk>.*)/$',
        SubitemDelete.as_view(),
        name='subitem_delete'),
    url(r'^inventory/subitem/update/(?P<pk>.*)/$',
        SubitemUpdate.as_view(),
        name='subitem_update'),
    ]
