# Generated by Django 2.2.16 on 2020-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_deaccession',
            field=models.DateField(blank=True, null=True),
        ),
    ]
