# Generated by Django 2.2.16 on 2020-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_date_deaccession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=3000)),
                ('view', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('view', 'code')},
            },
        ),
    ]
