# Generated by Django 2.2.17 on 2020-12-19 22:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def initialize_style(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StyleVersion = apps.get_model("inventory", "StyleVersion")
    version = StyleVersion(
        name="Baseline",
        number=1.0,
        currently_live=True,
        currently_test=True)
    version.save()
    StyleProperty = apps.get_model("inventory", "StyleProperty")
    StyleValue = apps.get_model("inventory", "StyleValue")
    init_prop = ['color', 'background-color', 'border-color']
    for p in init_prop:
        value = '#ffc0cb'
        hover_value = '#fe019a'
        prop1 = StyleProperty(
            selector='.inventory-primary',
            description='the color of all active buttons',
            style_property=p)
        prop2 = StyleProperty(
            selector='.inventory-primary',
            description='the color of all active buttons',
            pseudo_class='hover',
            style_property=p)
        prop1.save()
        prop2.save()
        if p == 'color':
            value='#fff'
            hover_value='#fff'
        value1 = StyleValue(
            style_property=prop1,
            style_version=version,
            value=value)
        value2 = StyleValue(
            style_property=prop2,
            style_version=version,
            value=hover_value)
        value1.save()
        value2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('pseudo_class', models.CharField(blank=True, max_length=128, null=True)),
                ('style_property', models.CharField(max_length=300)),
                ('value_type', models.CharField(choices=[('color', 'color')], default='color', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['selector', 'pseudo_class', 'style_property'],
                'unique_together': {('selector', 'pseudo_class', 'style_property')},
            },
        ),
        migrations.CreateModel(
            name='StyleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currently_live', models.BooleanField(default=False)),
                ('currently_test', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'number'],
                'unique_together': {('name', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StyleValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('style_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StyleProperty')),
                ('style_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StyleVersion')),
            ],
            options={
                'ordering': ['style_version', 'style_property'],
                'unique_together': {('style_property', 'style_version')},
            },
        ),
        migrations.RunPython(initialize_style),
    ]
