# Generated by Django 2.2.17 on 2021-02-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20201221_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleselector',
            name='target_element_usage',
        ),
        migrations.CreateModel(
            name='UserStylePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StyleVersion')),
            ],
        ),
    ]
