# Generated by Django 2.2.17 on 2021-02-16 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20201221_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleselector',
            name='target_element_usage',
        ),
        migrations.AddField(
            model_name='styleversion',
            name='previewed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
