# Generated by Django 2.2.17 on 2021-01-24 13:38

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('inventory', '0005_auto_20201221_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylevalue',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
