# Generated by Django 2.2.19 on 2021-03-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_itemimage_main_image'),
        ('inventory', '0007_auto_20210322_2148'),
    ]

    operations = [
    ]
