# Generated by Django 2.2.19 on 2021-04-02 22:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_merge_20210329_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, on_update=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
