# Generated by Django 3.0.14 on 2021-12-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_used',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subitem',
            name='size',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
