# Generated by Django 3.0.14 on 2022-01-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20211221_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sz',
            field=models.TextField(blank=True),
        ),
    ]
