from .basic_item_form import BasicItemForm
from .physical_item_form import PhysicalItemForm
from .further_detail_form import FurtherDetailForm
from .image_upload_form import ImageUploadForm
from .item_image_form import ItemImageForm
from .image_associate_form import ImageAssociateForm
from .image_associate_meta_form import ImageAssociateMetaForm
from .color_style_value_form import ColorStyleValueForm
from .label_form import LabelForm
